allowBuilds:
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - "@takumi-rs/core@2.0.0-beta.9"
  - "@takumi-rs/helpers@2.0.0-beta.9"
  - "@takumi-rs/wasm@2.0.0-beta.9"
  - takumi-js@2.0.0-beta.9
