export const background: Record<string, string> = {
  Fortnite: "fortnite.jpg",
  "Les Kardashian": "kardashian.webp",
  "Fast & Furious": "fast-furious.jpg",
  TikTok: "tiktok.jpeg",
  Pokémon: "pokemon.png",
  Twilight: "twilight.jpg",
  "La Casa de Papel": "casa-papel.jpeg",
  "Squid Game": "squid-game.webp",
  Minecraft: "minecraft.jpg",
  "Dragon Ball Z": "dragon-ball.jpg",
  "Les Simpson": "simpson.jpg",
  Naruto: "naruto.jpg",
  "One Piece": "one-piece.png",
  "Le MCU": "mcu.jpg",
  "Stranger Things": "stranger-things.jpg",
  "Game of Thrones": "game-thrones.jpg",
  Roblox: "roblox.jpg",
  "Call of Duty": "callof.jpg",
  "50 nuances de Grey": "shades.jpg",
  "Justin Bieber": "bieber.jpg",
  BTS: "bts.jpg",
  "Candy Crush": "candy-crush.jpg",
  "La télé-réalité": "montoya.jpeg",
  Barbie: "barbie.jpg",
  Transformers: "transformers.jpeg",
  "Gossip Girl": "gossip.jpg",
  "Desperate Housewives": "housewives.jpg",
  "Britney Spears": "spears.jpg",
  Shrek: "shrek.jpg",
  "Bob l'éponge": "spongebob.jpg",
  "Les Minions": "minions.jpg",
  "Family Guy": "family.jpg",
  "Le Guide du Zizi Sexuel": "zizi.jpg",
  "Elmer l'éléphant": "elmer.jpg",
  "Bref 2": "bref2.jpg",
  "Les Tuche 5": "tuche5.jpg",
  "Oui-Oui": "oui-oui.jpg",
  "Les Schtroumpfs": "schtroumpfs.jpg",
  "Les Razmoket": "razmoket.jpg",
  "Kung Fu Panda": "kung-fu.jpeg",
  "Les Tortues Ninja": "tortues.jpeg",
  "Tom-Tom et Nana": "tom-nana.png",
  "Les films de Christian Clavier": "clavier.png",
  "Bienvenue chez les Ch'tis": "chtis.jpeg",
  "Les dessins de Plantu": "plantu.png",
  "Le prince de Motordu": "motordu.jpg",
  "La Grande Vadrouille": "vadrouille.jpg",
  "La guerre des boutons": "boutons.jpg",
  Snoopy: "snoopy.jpg",
  "Les wojaks": "wojaks.jpg",
  "Les memes de 2010": "memes.jpg",
  "Le congrès de Tours": "tours.jpg",
  "La révolution d'octobre": "octobre.jpg",
  Inception: "inception.jpg",
  Joker: "joker.jpg",
  "Foot 2 rue": "foot2rue.jpeg",
  "Le roi lion": "roi-lion.jpeg",
  "Les Aristochats": "aristochats.jpeg",
  "Corneil et Bernie": "corneil.jpg",
  "Les Ratz": "ratz.jpg",
  "Le Brat Summer": "brat.jpeg",
  "Les zinzins de l'espace": "zinzins.jpg",
  "Fight Club": "fight-club.jpg",
  Interstellar: "interstellar.jpg",
  "Les Soprano": "soprano.jpg",
  "The Wire": "wire.jpg",
  "Twin Peaks": "twin-peaks.jpeg",
  "Brooklyn Nine-Nine": "brooklyn.jpg",
  "The Office": "office.jpg",
  "Breaking Bad": "breaking-bad.jpg",
  "Wallace et Gromit": "wallace.jpg",
  "Le Cerfa 15481*01": "cerfa.jpg",
  "Lana del Rey": "lana.jpeg",
  PZK: "pzk.jpg",
  "Le jeu de Guardiola": "guardiola.jpg",
  "Le gay latino": "latino.jpeg",
  "Questions pour un champion": "champion.jpg",
  "La famille pirate": "pirate.jpeg",
  "Les mystérieuses cités d'or": "cites.jpg",
  "La vie de Tintin": "tintin.jpg",
  Squeezie: "squeezie.jpeg",
  "McFly et Carlito": "mcfly.jpg",
  Michou: "michou.jpg",
  Inoxtag: "inoxtag.jpg",
  "Bojack Horseman": "bojack.png",
  Vald: "vald.jpeg",
  "Alpha Wann": "alpha.jpg",
  "Les films de Scorsese": "scorsese.jpg",
  Severance: "severance.jpg",
  "Léna Situations": "lena.jpg",
  "Frédéric Beigbeder": "beigbeder.jpg",
  PNL: "pnl.jpg",
  SCH: "sch.jpg",
  "Action Directe": "action.jpg",
  "Les Brigades Rouges": "rouges.jpg",
  "Les Black Panthers": "panthers.jpeg",
  "La Fraction Armée Rouge": "rouge.jpg",
  "L'OTAN": "otan.jpg",
  "Le KGB": "kgb.jpg",
  "La Stasi": "stasi.jpg",
  "La CIA": "cia.jpg",
  "Splatoon 3": "splatoon.jpeg",
  "Les Totally Spies": "spies.jpg",
  "L'Attaque des Titans": "titans.jpg",
  Vikings: "vikings.jpeg",
  "Vinland Saga": "vinland.jpg",
  Berserk: "berserk.jpg",
  "Flight Simulator": "flight.jpg",
  "Le Programme Spatial Basque": "basque.jpg",
  "La dépression": "depression.jpg",
  Nasdas: "nasdas.jpg",
  "La cité de la peur": "peur.jpg",
  "Skibidi Toilet": "skibidi.jpg",
  "Tibo InShape": "tibo.jpeg",
  Matrix: "matrix.jpg",
  "Frenchie Shore": "frenchie.jpeg",
  "La dialectique": "dialectique.png",
  "La phénoménologie": "phenomenologie.jpeg",
  "Le matérialisme": "materialisme.png",
  "Le structuralisme": "structuralisme.jpg",
  "L'IA": "ia.jpg",
  "Le HTML": "html.jpg",
  "Retour vers le futur": "futur.jpg",
  "Le Comte de Monte-Cristo": "monte-cristo.jpeg",
  "Soleil Vert": "soleil.jpg",
  "Mr. Robot": "robot.jpg",
  MrBeast: "beast.jpg",
  "Le situationnisme": "situationnisme.jpg",
  "L'accident de Lady Di": "lady-di.jpg",
  "Les NFT": "nft.png",
  "Among Us": "among.jpg",
  "The Handmaid's Tale": "handmaid.jpg",
  "Quentin Dupieux": "dupieux.jpeg",
  "The White Lotus": "lotus.jpg",
  "The Substance": "substance.jpg",
  Parasite: "parasite.jpg",
  "L'URSSAF": "urssaf.webp",
  "Grey's Anatomy": "anatomy.jpeg",
  "Cars 2": "cars.jpg",
  "Le code de la route": "code-route.jpg",
  "Le Capital": "capital.jpeg",
  "L'hétéronormativité": "heteronormativite.jpg",
  "Le patriarcat": "patriarcat.jpeg",
  "Le nucléaire": "nucleaire.jpg",
  "La menace nucléaire": "menace.jpeg",
  "Le dérèglement climatique": "climatique.jpeg",
  "La cuisine": "cuisine.jpeg",
  "La conscience de classe": "classe.jpeg",
  "La lutte des classes": "lutte.webp",
  "La dictature du prolétariat": "dictature.jpg",
  "La division du travail": "travail.jpg",
  "La plus-value": "plus-value.jpeg",
  "L'endométriose": "endometriose.jpg",
  "L'internationalisme": "internationalisme.jpg",
  "La commune de Paris": "commune.jpg",
  "L'impérialisme": "imperialisme.png",
  "Le petit prince": "prince.jpeg",
  "Le château dans le ciel": "chateau.jpg",
  "Le voyage de Chihiro": "chihiro.jpg",
  "Le tombeau des lucioles": "lucioles.jpeg",
  "Princesse Mononoké": "mononoke.jpeg",
  "Le château ambulant": "ambulant.jpg",
  "La prison": "prison.jpg",
  Gladiator: "gladiator.jpg",
  Intouchables: "intouchables.jpeg"
};
