export const foreground: Record<string, string> = {
  "Michel Foucault": "foucault",
  "Simone de Beauvoir": "beauvoir",
  "Jean-Paul Sartre": "sartre",
  "Hannah Arendt": "arendt",
  "Jacques Derrida": "derrida",
  "Judith Butler": "butler",
  "Gilles Deleuze": "deleuze",
  "Slavoj Žižek": "zizek",
  "Noam Chomsky": "chomsky",
  "Pierre Bourdieu": "bourdieu",
  "Roland Barthes": "barthes",
  "Simone Weil": "weil",
  "Albert Camus": "camus",
  "Friedrich Nietzsche": "nietzsche",
  "Emmanuel Kant": "kant",
  "Karl Marx": "marx",
  "Sigmund Freud": "freud",
  "Carl Jung": "jung",
  "Émile Durkheim": "durkheim",
  "Claude Lévi-Strauss": "levi-strauss",
  "Yuval Noah Harari": "harari",
  "Umberto Eco": "eco",
  "Walter Benjamin": "benjamin",
  "Theodor Adorno": "adorno",
  "Jean Baudrillard": "baudrillard",
  "Julia Kristeva": "kristeva",
  "Gayatri Spivak": "spivak",
  "Edward Saïd": "said",
  "Frantz Fanon": "fanon",
  "bell hooks": "hooks",
  "Donna Haraway": "haraway",
  "Achille Mbembe": "mbembe",
  "Édouard Glissant": "glissant",
  "Bernard-Henri Lévy": "bhl",
  "Edgar Morin": "morin",
  "Alain Badiou": "badiou",
  "Étienne Klein": "klein",
  "Monique Wittig": "wittig",
  "Hélène Cixous": "cixous",
  Confucius: "confucius",
  "Max et Lili": "max-lili",
  Tchoupi: "tchoupi",
  Theodora: "theodora",
  "Andrea Dworkin": "dworkin",
  "Michel Onfray": "onfray",
  "Alain Finkielkraut": "finkielkraut",
  "Raphaël Enthoven": "enthoven",
  "Pierre Desproges": "desproges",
  Coluche: "coluche",
  "Jean-Marie Bigard": "bigard",
  "Friedrich Engels": "engels",
  Lénine: "lenine",
  "Mao Zedong": "zedong",
  "Rosa Luxemburg": "luxemburg",
  "Antonio Gramsci": "gramsci",
  "Mikhaïl Bakounine": "bakounine",
  "Angela Davis": "davis",
  "Aimé Césaire": "cesaire",
  "Léopold Sédar Senghor": "senghor",
  "Bernard Friot": "friot",
  "Frédéric Lordon": "lordon",
  "Jean-Luc Mélenchon": "melenchon",
  "Franz Kafka": "kafka",
  "George Orwell": "orwell",
  "Aldous Huxley": "huxley",
  "Margaret Atwood": "atwood",
  Avicenne: "avicenne",
  Averroès: "averroes",
  Robespierre: "robespierre",
  "Malcolm X": "malcolm",
  "Che Guevara": "guevara",
  "Nelson Mandela": "mandela",
  "W.E.B. Du Bois": "dubois",
  "Maître Eckhart": "eckhart",
  Heidegger: "heidegger",
  Schopenhauer: "schopenhauer",
  Descartes: "descartes",
  Spinoza: "spinoza",
  "Henri Lefebvre": "lefebvre",
  "Carl Schmitt": "schmitt",
  "Georges Bataille": "bataille",
  "Hermann Hesse": "hesse",
  "Paul Nizan": "nizan",
  "Frida Kahlo": "kahlo",
  "Salvador Allende": "allende",
  "Thomas Sankara": "sankara",
  Platon: "platon",
  Aristote: "aristote",
  Socrate: "socrate",
  Bordiga: "bordiga",
  "Georg Lukács": "lukacs",
  "Lucien Goldmann": "goldmann",
  "Andreas Malm": "malm",
  "Naomi Klein": "naomi-klein",
  "David Graeber": "graeber",
  "Johann Chapoutot": "chapoutot",
  "Olympe de Gouges": "gouges",
  "Erich Honecker": "honecker",
  "Fidel Castro": "castro",
  "Hugo Chávez": "chavez",
  "Mikhaïl Gorbatchev": "gorbatchev",
  "Léon Trotski": "trotski",
  Usul: "usul",
  "Ludwig Wittgenstein": "wittgenstein",
  "Gabriel García Márquez": "marquez",
  "Albert Einstein": "einstein",
  "Isabel Allende": "isabel-allende",
  "Idriss Aberkane": "aberkane",
  "Le Pr Raoult": "raoult",
  "Emmanuel Macron": "macron-",
  "Jean-Luc Godard": "godard",
  "Chico Buarque": "buarque",
  "Ada Lovelace": "lovelace",
  "Alan Turing": "turing",
  "Les Pinçon-Charlot": "pincon-charlot",
  "Marie Curie": "curie",
  "Christine Delphy": "delphy",
  "Françoise Héritier": "heritier",
  "Françoise Dolto": "dolto",
  "Christine de Pizan": "pizan",
  "Mary Wollstonecraft": "wollstonecraft",
  "Jane Austen": "austen",
  "Virginia Woolf": "woolf",
  "George Sand": "sand",
  "Marguerite Duras": "duras",
  "Annie Ernaux": "ernaux",
  "Françoise Sagan": "sagan",
  "Marguerite Yourcenar": "yourcenar",
  Colette: "colette",
  "Agnès Varda": "varda",
  "Chantal Akerman": "akerman",
  "Sofia Coppola": "coppola",
  "Mouammar Kadhafi": "gaddafi",
  "Oussamma Ammar": "ammar",
  "Paul B. Preciado": "preciado",
  "Ursula K. Le Guin": "guin",
  "Léna Situations": "lena",
  "Frédéric Beigbeder": "beigbeder",
  JUL: "jul",
  "Christian Ingrao": "ingrao",
  "André Gide": "gide",
  "Anatole France": "france",
  "Jean-Marc Rouillan": "rouillan",
  "Oussama Ben Laden": "ben-laden",
  Toi: "toi",
  "Fiodor Dostoïevski": "dostoievski",
  "Léon Tolstoï": "tolstoi",
  "Renaud Camus": "r-camus",
  "Werner Herzog": "herzog",
  "David Lynch": "lynch",
  "Céline Sciamma": "sciamma",
  "Houria Bouteldja": "bouteldja",
  "Jacques Rancière": "ranciere",
  "Jacques Vergès": "verges",
  "Françoise Vergès": "f-verges",
  Hegel: "hegel",
  "Karl Popper": "popper",
  "Louis-Ferdinand Céline": "celine",
  "Bruno Retailleau": "retailleau",
  "Alexandre Astier": "astier",
  "Charles Darwin": "darwin",
  "Charles De Gaulle": "de-gaulle",
  "Marcel Proust": "proust",
  "Victor Hugo": "hugo",
  "Alfred de Musset": "musset",
  "Guy Debord": "debord",
  "Cyril Hanouna": "hanouna",
  "Jean d'Ormesson": "ormesson",
  "Max Weber": "weber",
  "Michel Houellebecq": "houellebecq",
  "Yann Moix": "moix",
  "Édouard Louis": "louis",
  SCH: "sch",
  "Didier Eribon": "eribon",
  "Geoffroy de Lagasnerie": "lagasnerie",
  "Hugo Décrypte": "hugo-decrypte",
  "Deng Xiaoping": "deng",
  "Xi Jinping": "xi",
  "Raphaël Glucksmann": "glucksmann",
  "Alexander Grothendieck": "grothendieck",
  "Nathalie Arthaud": "arthaud",
  "Arlette Laguiller": "laguiller",
  "Jacques Lacan": "lacan",
  "Félix Guattari": "guattari",
  Rohff: "rohff",
  "Diego Maradona": "maradona",
  "Al Capone": "capone",
  "Augustin Shackelpopoulos": "shackelpopoulos",
  "La Bible": "bible",
  "Le Code Civil": "code-civil",
  "Le Petit Livre Rouge": "livre-rouge"
};
