export const background: Record<string, string> = {
  Fortnite: "fortnite.jpg",
  "Les Kardashian": "kardashian.webp",
  "Fast & Furious": "fast-furious.jpg",
  TikTok: "tiktok.jpeg",
  Pokémon: "pokemon.png",
  Twilight: "twilight.jpg",
  "La Casa de Papel": "casa-papel.jpeg",
  "Squid Game": "squid-game.webp",
  Minecraft: "minecraft.jpg",
  "Dragon Ball Z": "dragon-ball.jpg",
  "Les Simpson": "simpson.jpg",
  Naruto: "naruto.jpg",
  "One Piece": "one-piece.png",
  "Le MCU": "mcu.jpg",
  "Stranger Things": "stranger-things.jpg",
  "Game of Thrones": "game-thrones.jpg",
  Roblox: "roblox.jpg",
  "Call of Duty": "callof.jpg",
  "Fifty Shades of Grey": "shades.jpg",
  "Justin Bieber": "bieber.jpg",
  BTS: "bts.jpg",
  "Candy Crush": "candy-crush.jpg",
  "La télé-réalité": "montoya.jpeg",
  Barbie: "barbie.jpg",
  Transformers: "transformers.jpeg",
  "Gossip Girl": "gossip.jpg",
  "Desperate Housewives": "housewives.jpg",
  "Britney Spears": "spears.jpg",
  Shrek: "shrek.jpg",
  "Bob l'éponge": "spongebob.jpg",
  "Les Minions": "minions.jpg",
  "Family Guy": "family.jpg",
  "Le Guide du Zizi Sexuel": "zizi.jpg",
  "Elmer l'éléphant": "elmer.jpg",
  "Bref 2": "bref2.jpg",
  "Les Tuche 5": "tuche5.jpg",
  "Oui-Oui": "oui-oui.jpg",
  "Les Schtroumpfs": "schtroumpfs.jpg",
  "Les Razmoket": "razmoket.jpg",
  "Kung Fu Panda": "kung-fu.jpeg",
  "Les Tortues Ninja": "tortues.jpeg",
  "Tom-Tom et Nana": "tom-nana.png",
  "Les films de Christian Clavier": "clavier.png",
  "Bienvenue chez les Ch'tis": "chtis.jpeg",
  "Les dessins de Plantu": "plantu.png",
  "Le prince de Motordu": "motordu.jpg",
  "La Grande Vadrouille": "vadrouille.jpg",
  "La guerre des boutons": "boutons.jpg",
  Snoopy: "snoopy.jpg",
  "Les wojaks": "wojaks.jpg",
  "Les memes de 2010": "memes.jpg",
  "Le congrès de Tours": "tours.jpg",
  "La révolution d'octobre": "octobre.jpg",
  Inception: "inception.jpg",
  Joker: "joker.jpg",
  "Foot 2 rue": "foot2rue.jpeg",
  "Le roi lion": "roi-lion.jpeg",
  "Les Aristochats": "aristochats.jpeg",
  "Corneil et Bernie": "corneil.jpg",
  "Les Ratz": "ratz.jpg",
  "Le Brat Summer": "brat.jpeg",
  "Les zinzins de l'espace": "zinzins.jpg",
  "Fight Club": "fight-club.jpg",
  Interstellar: "interstellar.jpg",
  "Les Soprano": "soprano.jpg",
  "The Wire": "wire.jpg",
  "Twin Peaks": "twin-peaks.jpeg",
  "Brooklyn Nine-Nine": "brooklyn.jpg",
  "The Office": "office.jpg",
  "Breaking Bad": "breaking-bad.jpg",
  "Wallace et Gromit": "wallace.jpg",
  "Le Cerfa 15481*01": "cerfa.jpg",
  "Lana del Rey": "lana.jpeg",
  PZK: "pzk.jpg",
  "Le jeu de Guardiola": "guardiola.jpg",
  "Le gay latino": "latino.jpeg",
  "Questions pour un champion": "champion.jpg",
  "La famille pirate": "pirate.jpeg",
  "Les mystérieuses cités d'or": "cites.jpg",
  "La vie de Tintin": "tintin.jpg",
  Squeezie: "squeezie.jpeg",
  "McFly et Carlito": "mcfly.jpg",
  Michou: "michou.jpg",
  Inoxtag: "inoxtag.jpg",
  "Bojack Horseman": "bojack.jpeg",
  Vald: "vald.jpeg",
  "Alpha Wann": "alpha.jpg",
  "Les films de Scorsese": "scorsese.jpg"
};

export const foreground: Record<string, string> = {
  "Michel Foucault": "foucault",
  "Simone de Beauvoir": "beauvoir",
  "Jean-Paul Sartre": "sartre",
  "Hannah Arendt": "arendt",
  "Jacques Derrida": "derrida",
  "Judith Butler": "butler",
  "Gilles Deleuze": "deleuze",
  "Slavoj Žižek": "zizek",
  "Noam Chomsky": "chomsky",
  "Pierre Bourdieu": "bourdieu",
  "Roland Barthes": "barthes",
  "Simone Weil": "weil",
  "Albert Camus": "camus",
  "Friedrich Nietzsche": "nietzsche",
  "Emmanuel Kant": "kant",
  "Karl Marx": "marx",
  "Sigmund Freud": "freud",
  "Carl Jung": "jung",
  "Émile Durkheim": "durkheim",
  "Claude Lévi-Strauss": "levi-strauss",
  "Yuval Noah Harari": "harari",
  "Umberto Eco": "eco",
  "Walter Benjamin": "benjamin",
  "Theodor Adorno": "adorno",
  "Jean Baudrillard": "baudrillard",
  "Julia Kristeva": "kristeva",
  "Gayatri Spivak": "spivak",
  "Edward Saïd": "said",
  "Frantz Fanon": "fanon",
  "bell hooks": "hooks",
  "Donna Haraway": "haraway",
  "Achille Mbembe": "mbembe",
  "Édouard Glissant": "glissant",
  "Bernard-Henri Lévy": "bhl",
  "Edgar Morin": "morin",
  "Alain Badiou": "badiou",
  "Étienne Klein": "klein",
  "Monique Wittig": "wittig",
  "Hélène Cixous": "cixous",
  Confucius: "confucius",
  "Max et Lili": "max-lili",
  Tchoupi: "tchoupi",
  Theodora: "theodora",
  "Andrea Dworkin": "dworkin",
  "Michel Onfray": "onfray",
  "Alain Finkielkraut": "finkielkraut",
  "Raphaël Enthoven": "enthoven",
  "Pierre Desproges": "desproges",
  Coluche: "coluche",
  "Jean-Marie Bigard": "bigard",
  "Friedrich Engels": "engels",
  Lénine: "lenine",
  "Mao Zedong": "zedong",
  "Rosa Luxemburg": "luxemburg",
  "Antonio Gramsci": "gramsci",
  "Michel Bakounine": "bakounine",
  "Angela Davis": "davis",
  "Aimé Césaire": "cesaire",
  "Léopold Sédar Senghor": "senghor",
  "Bernard Friot": "friot",
  "Frédéric Lordon": "lordon",
  "Jean-Luc Mélenchon": "melenchon",
  "Franz Kafka": "kafka",
  "George Orwell": "orwell",
  "Aldous Huxley": "huxley",
  "Margaret Atwood": "atwood",
  Avicenne: "avicenne",
  Averroès: "averroes",
  Robespierre: "robespierre",
  "Malcolm X": "malcolm",
  "Che Guevara": "guevara",
  "Nelson Mandela": "mandela",
  "W.E.B. Du Bois": "dubois",
  "Maître Eckhart": "eckhart",
  Heidegger: "heidegger",
  Schopenhauer: "schopenhauer",
  Descartes: "descartes",
  Spinoza: "spinoza",
  "Henri Lefebvre": "lefebvre",
  "Carl Schmitt": "schmitt",
  "Georges Bataille": "bataille",
  "Hermann Hesse": "hesse",
  "Paul Nizan": "nizan",
  "Frida Kahlo": "kahlo",
  "Salvador Allende": "allende",
  "Thomas Sankara": "sankara",
  Platon: "platon",
  Aristote: "aristote",
  Socrate: "socrate",
  Bordiga: "bordiga",
  "Georg Lukács": "lukacs",
  "Lucien Goldmann": "goldmann",
  "Andreas Malm": "malm",
  "Naomi Klein": "naomi-klein",
  "David Graeber": "graeber",
  "Johann Chapoutot": "chapoutot",
  "Olympe de Gouges": "gouges",
  "Erich Honecker": "honecker",
  "Fidel Castro": "castro",
  "Hugo Chávez": "chavez",
  "Mikhaïl Gorbatchev": "gorbatchev",
  "Léon Trotski": "trotski",
  Usul: "usul",
  "Ludwig Wittgenstein": "wittgenstein",
  "Gabriel García Márquez": "marquez",
  "Albert Einstein": "einstein",
  "Isabel Allende": "isabel-allende",
  "Idriss Aberkane": "aberkane",
  "Le Pr Raoult": "raoult",
  "Emmanuel Macron": "macron",
  "Jean-Luc Godard": "godard",
  "Chico Buarque": "buarque",
  "Ada Lovelace": "lovelace",
  "Alan Turing": "turing",
  "Les Pinçon-Charlot": "pincon-charlot",
  "Marie Curie": "curie",
  "Christine Delphy": "delphy",
  "Françoise Héritier": "heritier",
  "Françoise Dolto": "dolto",
  "Christine de Pizan": "pizan",
  "Mary Wollstonecraft": "wollstonecraft",
  "Jane Austen": "austen",
  "Virginia Woolf": "woolf",
  "George Sand": "sand",
  "Marguerite Duras": "duras",
  "Annie Ernaux": "ernaux",
  "Françoise Sagan": "sagan",
  "Marguerite Yourcenar": "yourcenar",
  Colette: "colette",
  "Agnès Varda": "varda",
  "Chantal Akerman": "akerman",
  "Sofia Coppola": "coppola",
  "Mouammar Kadhafi": "gaddafi",
  "Oussamma Ammar": "ammar",
  "Paul B. Preciado": "preciado",
  "Ursula K. Le Guin": "guin",
  Oklou: "oklou"
};

function getRandomElement<T>(array: T[]): T {
  return array[Math.floor(Math.random() * array.length)];
}

export function getRandomCombination() {
  return {
    background: getRandomElement(Object.keys(background)),
    foreground: getRandomElement(Object.keys(foreground))
  };
}
